#!/usr/bin/env python3
import sys, os

_src = os.path.join(os.path.dirname(os.path.realpath(__file__)), "src")
if os.path.isdir(_src) and _src not in sys.path:
    sys.path.insert(0, _src)

import aniterm
aniterm.main()
